controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gimbal_controller:
      type: joint_trajectory_controller/JointTrajectoryController

gimbal_controller:
  ros__parameters:
    joints:
      - yaw_joint
      - pitch_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 1.0

joint_state_broadcaster:
  ros__parameters: {}
